SRCS=hello.c
KMOD=hello

# Uncomment the following lines to cross compile to ARM64 architecture for the Raspberry Pi
#CC=clang --target=aarch64-unknown-freebsd
#MACHINE_ARCH=aarch64
#MACHINE=arm64

.include <bsd.kmod.mk>

